publication_name: "NHS Dental Statistics for England"
publication_sub_name: "2024/2025"
publication_date: "28 August 2025"
responsible_statistician: "Grace Libby"
stats_survey_link: "https://online1.snapsurveys.com/Official_Statistics_Feedback"
