publication_name: "NHS Dental Statistics for England"
publication_sub_name: "2024/2025"
publication_date: "28 August 2025"
responsible_statistician: "Grace Libby"

stats_survey_link: "https://online1.snapsurveys.com/Official_Statistics_Feedback"
background_link: 
national_cont_excel_link:
geography_cont_excel_link:
workforce_excel_table_link:
national_pat_link:
geography_pat_link:

cover_sheet_sub_title_nat_activity: "National activity overview 2019/20 to 2024/25"
cover_sheet_sub_title_geo_activity_contract: "Contract location geographical activity 2019/20 to 2024/25"
cover_sheet_sub_title_geo_activity_patient: "Patient location geographical activity 2019/20 to 2024/25"
cover_sheet_sub_title_workforce:
table_sheet_title_fy: "England 2019/20 to 2024/25"



