publication_name: "NHS Dental Statistics for England"
publication_sub_name: "2023/24"
publication_date: "22 August 2024"
responsible_statistician: "Grace Libby"
stats_survey_link: "https://online1.snapsurveys.com/Official_Statistics_Feedback"
